### PR TITLE
Automaticaly add enctype to the form

### PR DESCRIPTION
**Pull request by aadutskevich**
The same issue as it was with standart yii2 fileInput https://github.com/yiisoft/yii2/issues/8779

### CODE REVIEW

**Comment by kartik-v** [comment]
Will not work here the way the code is written - because this class is not an instance of `yii\widgets\ActiveField` unlike the `yii fileinput` which is an activefield instance.

This FileInput widget here can be used with and without a `form` and via ajax as well... so it makes sense for users to set the `enctype` property to the form based on their own need (as it is not mandatory for the other cases like ajax).

**Comment by aadutskevich** [comment]
Ok, let we add an instance check, So if we use widget with ActiveField then the form enctype option will be created.

	    `if ($this->field instanceof \yii\widgets\ActiveField && !isset($this->field->form->options['enctype'])) {
		    $this->field->form->options['enctype'] = 'multipart/form-data';
	    }`

**Comment by kartik-v** [comment]
Reiterating.... `$this` is an instance of `yii\base\Widget` and does not have `form` or `field` methods.

**Comment by kartik-v** [comment]
Ok -- this above code will work for `InputWidget`... will figure out and include this...

**Pull request closed without merging**
